/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JualDialog.java
 *
 * Created on Mar 13, 2010, 11:50:02 PM
 */
package khannedy.enterprise.penjualan.form.sell;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;
import khannedy.enterprise.penjualan.form.Application;
import khannedy.enterprise.penjualan.form.Dialogable;

/**
 *
 * @author echo
 */
public class SellDialog extends javax.swing.JDialog implements Dialogable {

    private TableModelDetailTransaksi tableModelDetailTransaksi;

    private SellDialogController controller;

    /** Creates new form JualDialog */
    public SellDialog(Application parent) {
	super(parent, true);
	initComponents();

	tableModelDetailTransaksi = new TableModelDetailTransaksi();
	tabelTransaksi.setModel(tableModelDetailTransaksi);

	controller = new SellDialogController(this);

	buttonJual.addActionListener(controller);
	buttonTambah.addActionListener(controller);
	buttonHapus.addActionListener(controller);
    }

    public JLabel getLabelTotal() {
	return labelTotal;
    }

    public JButton getButtonHapus() {
	return buttonHapus;
    }

    public JButton getButtonJual() {
	return buttonJual;
    }

    public JButton getButtonTambah() {
	return buttonTambah;
    }

    public JTable getTabelTransaksi() {
	return tabelTransaksi;
    }

    public TableModelDetailTransaksi getTableModelDetailTransaksi() {
	return tableModelDetailTransaksi;
    }

    public JTextField getTextBanyak() {
	return textBanyak;
    }

    public JTextField getTextKodeBarang() {
	return textKodeBarang;
    }

    public JTextField getTextNamaPembeli() {
	return textNamaPembeli;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textKodeBarang = new javax.swing.JTextField();
        textBanyak = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelTransaksi = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        labelTotal = new javax.swing.JLabel();
        buttonJual = new javax.swing.JButton();
        buttonTambah = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        textNamaPembeli = new javax.swing.JTextField();
        buttonHapus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Kode Barang :");

        textKodeBarang.setFont(new java.awt.Font("Dialog", 1, 36));

        textBanyak.setFont(new java.awt.Font("Dialog", 1, 36));

        jLabel2.setText("Banyak :");

        jScrollPane1.setViewportView(tabelTransaksi);

        jLabel3.setText("Total :");

        labelTotal.setFont(new java.awt.Font("Dialog", 1, 36));
        labelTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelTotal.setText("Rp. 0");

        buttonJual.setFont(new java.awt.Font("Dialog", 1, 36));
        buttonJual.setText("JUAL");

        buttonTambah.setText("TAMBAH");

        jLabel5.setText("Nama Pembeli :");

        buttonHapus.setText("HAPUS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textNamaPembeli, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
                        .addGap(141, 141, 141))
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonJual, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(329, 329, 329))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
                                    .addComponent(textKodeBarang, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonTambah, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addComponent(textBanyak, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                            .addComponent(buttonHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textNamaPembeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textKodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBanyak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonTambah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                    .addComponent(buttonHapus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(labelTotal)
                    .addComponent(buttonJual))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonHapus;
    private javax.swing.JButton buttonJual;
    private javax.swing.JButton buttonTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JTable tabelTransaksi;
    private javax.swing.JTextField textBanyak;
    private javax.swing.JTextField textKodeBarang;
    private javax.swing.JTextField textNamaPembeli;
    // End of variables declaration//GEN-END:variables

    public void dialog() {
	controller.resetController();
	setVisible(true);
    }
}
