/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Application.java
 *
 * Created on Mar 12, 2010, 4:46:58 PM
 */
package khannedy.enterprise.penjualan.form;

import javax.swing.JButton;

/**
 *
 * @author echo
 */
public class Application extends javax.swing.JFrame {

    private ApplicationController controller;

    /** Creates new form Application */
    public Application() {
	initComponents();

	controller = new ApplicationController(this);

	buttonMasterBarang.addActionListener(controller);
	buttonMasterKategori.addActionListener(controller);
	buttonJualBarang.addActionListener(controller);
	buttonMasterTransaksi.addActionListener(controller);
    }

    public JButton getButtonJualBarang() {
	return buttonJualBarang;
    }

    public JButton getButtonMasterBarang() {
	return buttonMasterBarang;
    }

    public JButton getButtonMasterKategori() {
	return buttonMasterKategori;
    }

    public JButton getButtonMasterTransaksi() {
	return buttonMasterTransaksi;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        buttonMasterBarang = new javax.swing.JButton();
        buttonMasterKategori = new javax.swing.JButton();
        buttonMasterTransaksi = new javax.swing.JButton();
        buttonJualBarang = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Penjualan");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Aplikasi Penjualan 1.0");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Menu :"));
        jPanel1.setLayout(new java.awt.GridLayout(2, 2));

        buttonMasterBarang.setText("Master Barang");
        jPanel1.add(buttonMasterBarang);

        buttonMasterKategori.setText("Master Kategori");
        jPanel1.add(buttonMasterKategori);

        buttonMasterTransaksi.setText("Master Transaksi");
        jPanel1.add(buttonMasterTransaksi);

        buttonJualBarang.setText("Jual Barang");
        jPanel1.add(buttonJualBarang);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 681, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 681, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                .addContainerGap())
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-707)/2, (screenSize.height-460)/2, 707, 460);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonJualBarang;
    private javax.swing.JButton buttonMasterBarang;
    private javax.swing.JButton buttonMasterKategori;
    private javax.swing.JButton buttonMasterTransaksi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
