/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CategoryDialog.java
 *
 * Created on Mar 13, 2010, 1:17:39 AM
 */
package khannedy.enterprise.penjualan.form.category;

import java.util.List;
import javax.persistence.EntityManager;
import javax.swing.JTable;
import khannedy.enterprise.penjualan.entity.Category;
import khannedy.enterprise.penjualan.form.Application;
import khannedy.enterprise.penjualan.form.Dialogable;
import khannedy.enterprise.penjualan.form.component.CrudPanel;
import khannedy.enterprise.penjualan.util.PersistenceContext;

/**
 *
 * @author echo
 */
public class CategoryDialog extends javax.swing.JDialog implements Dialogable {

    private CategoryUnitDialog categoryUnitDialog;

    private TableModelCategory tableModelCategory;

    private CategoryDialogController controller;

    /** Creates new form CategoryDialog */
    public CategoryDialog(Application application) {
	super(application, true);
	initComponents();

	categoryUnitDialog = new CategoryUnitDialog(this);

	controller = new CategoryDialogController(this, categoryUnitDialog);

	crudPanel.getButtonTambah().addActionListener(controller);
	crudPanel.getButtonUbah().addActionListener(controller);
	crudPanel.getButtonHapus().addActionListener(controller);
	crudPanel.getButtonSegarkan().addActionListener(controller);

	tableModelCategory = new TableModelCategory();
	tableKategori.setModel(tableModelCategory);
    }

    public TableModelCategory getTableModelCategory() {
	return tableModelCategory;
    }

    public JTable getTableKategori() {
	return tableKategori;
    }

    public CrudPanel getCrudPanel() {
	return crudPanel;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableKategori = new javax.swing.JTable();
        crudPanel = new khannedy.enterprise.penjualan.form.component.CrudPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Master Kategori");

        jScrollPane1.setViewportView(tableKategori);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
                    .addComponent(crudPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(crudPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-640)/2, (screenSize.height-480)/2, 640, 480);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private khannedy.enterprise.penjualan.form.component.CrudPanel crudPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableKategori;
    // End of variables declaration//GEN-END:variables

    public void dialog() {
	controller.refreshController();
	setVisible(true);
    }
}
