/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TransactionDialog.java
 *
 * Created on Mar 14, 2010, 2:30:39 PM
 */
package khannedy.enterprise.penjualan.form.transaksi;

import java.awt.Component;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import khannedy.enterprise.penjualan.form.Application;
import khannedy.enterprise.penjualan.form.Dialogable;

/**
 *
 * @author echo
 */
public class TransactionDialog extends javax.swing.JDialog implements Dialogable {

    private TableModelDetailTransaction tableModelDetailTransaction;

    private TableModelTransaction tableModelTransaction;

    private TransactionDialogController controller;

    /** Creates new form TransactionDialog */
    public TransactionDialog(Application parent) {
	super(parent, true);
	initComponents();

	controller = new TransactionDialogController(this);

	tableModelTransaction = new TableModelTransaction();
	tableTransaksi.setModel(tableModelTransaction);
	tableTransaksi.getSelectionModel().addListSelectionListener(controller);
	tableTransaksi.setDefaultRenderer(Calendar.class, new CalendarRenderer());

	tableModelDetailTransaction = new TableModelDetailTransaction();
	tableDetail.setModel(tableModelDetailTransaction);
    }

    public JTable getTableDetail() {
	return tableDetail;
    }

    public TableModelDetailTransaction getTableModelDetailTransaction() {
	return tableModelDetailTransaction;
    }

    public TableModelTransaction getTableModelTransaction() {
	return tableModelTransaction;
    }

    public JTable getTableTransaksi() {
	return tableTransaksi;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableTransaksi = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableDetail = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Master Transaksi");

        jScrollPane1.setViewportView(tableTransaksi);

        jScrollPane2.setViewportView(tableDetail);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 774, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 774, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-800)/2, (screenSize.height-600)/2, 800, 600);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableDetail;
    private javax.swing.JTable tableTransaksi;
    // End of variables declaration//GEN-END:variables

    public void dialog() {
	controller.refreshController();
	setVisible(true);
    }

    class CalendarRenderer extends DefaultTableCellRenderer {

	private DateFormat format;

	private Date date;

	public CalendarRenderer() {
	    format = new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");
	    date = new Date();
	}

	@Override
	public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
	    JLabel label = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
	    if (value != null && value instanceof Calendar) {
		Calendar calendar = (Calendar) value;
		date.setTime(calendar.getTimeInMillis());
		label.setText(format.format(date));
	    }
	    return label;
	}
    }
}
